### ISSUE TITLE
Test not passed under linux

### ISSUE THREAD

**Issue by zdm** [olegwtf/p5-AnyEvent-HTTP-Socks#1]
Subj.

I think, that problem in make_socks_server sur, which doesn't return correct hostname.
Problem appears after updating IO::Socket::Socks to the latest version v0.66.

**Comment by olegwtf** [comment]
make_socks_server() now may return IPv6 address. Need to add support for IPv6 addresses in `[addr]:port` format inside `AnyEvent::HTTP::Socks`

**Comment by zdm** [comment]
Or force make_socks_server return IPv4, as a quick fix.

**Comment by olegwtf** [comment]
New version released

**Comment by zdm** [comment]
Thanks.
